sudo: required
dist: trusty
language: bash
before_install:
- wget -O /tmp/gmirror.tar.gz https://github.com/sinkcup/gmirror/archive/2.5.0.tar.gz
- tar -zxvf /tmp/gmirror.tar.gz -C /tmp/
- cp /tmp/gmirror-2.5.0/*.sh ./
- bash ./before_install.sh
- sudo pip install mkdocs-bootswatch
install:
- bash ./portal.build.sh
script:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- bash ./before_upload.sh
- export PATH=$PATH:$PWD/qiniu/
- bash ./portal.upload.sh
